### ISSUE TITLE
version is not printed in VersionRecorder

### ISSUE THREAD

**Issue by oliv37** [quarkusio/quarkus-workshops#192]
I can't see the application version printed when using the `version-extension` in `rest-villains`

![image](https://user-images.githubusercontent.com/7140102/196050088-c4806b15-a92d-4553-886b-975587bb2b73.png)

As you can see, the `extension-version` is listed in the installed features, but the log `INFO  [io.qu.wo.su.ve.ru.VersionRecorder] (Quarkus Main Thread) Version: 1.0.0-SNAPSHOT` is never printed.

Surprisingly, when adding a `sysout` in `VersionRecorder.printVersion`, the log is correctly printed :

```
public void printVersion(String version) {
  System.out.println("Hello World !");
  Logger.getLogger(VersionRecorder.class.getName()).infof("Version: %s", version);
}
```
![image](https://user-images.githubusercontent.com/7140102/196050476-c77e81ca-304a-4784-af15-1edf70223155.png)

I can't figure out what is going on, maybe this is related to my laptop (I use elementary os). I get the same behavior with both versions of quarkus `2.9.2.Final` / `2.13.2.Final`

**Comment by cescoffier** [comment]
@geoand didn't we have an issue like that, where the logging subsystem is initialized after the first logged messages? I was thinking we were collecting the messages and printed them after the initialization, but I may be wrong.

**Comment by oliv37** [comment]
It's related to the [last part of the workshop](https://quarkus.io/quarkus-workshops/super-heroes/#extension). 

You may reproduce the problem by starting [rest-villain](https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes/super-heroes/rest-villains) and setting `quarkus.version.enabled=true` in [application.properties](https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/rest-villains/src/main/resources/application.properties#L23)

**Comment by geoand** [comment]
Thanks.

I'll try and have a look soon

**Comment by agoncal** [comment]
I've just updated the workshop to Quarkus 2.14.0 and the version is displayed ok. @oliv37 can you try with 2.14.0 please?

**Comment by oliv37** [comment]
@agoncal I tried with Quarkus 2.14.0 and it's working as expected, the version is correctly displayed.

I still see `<quarkus.platform.version>2.9.2.Final</quarkus.platform.version>` in the different `pom.xml` on **main** branch, do you plan to upgrade the version to the last version `2.14.0.Final`. By the way I see the properties are duplicated in all modules (rest-fights, rest-heroes, rest-villains...), it might be a good option to move the common maven configuration into the parent pom (super-parent-root).

**Comment by agoncal** [comment]
@oliv37 just to let you know that I've updated the code to Quarkus 2.15.3 (see #207) and the version is displayed ok. Can you check on your side with this new release?

**Comment by oliv37** [comment]
Still the same behavior on my side, it doesn't print anything when using the Logger. The version is correctly displayed when using `System.out.println`
